### ISSUE TITLE
error: 'RCC_BDCR_RTC_BIT' was not declared in this scope 

### ISSUE THREAD

**Issue by Liuyiming11** [ZulNs/STM32F1_RTC#1] opened 2019-11-07 03:05 UTC
D:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware D:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Liuyiming\AppData\Local\Arduino15\packages -tools D:\Program Files (x86)\Arduino\tools-builder -tools D:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Liuyiming\AppData\Local\Arduino15\packages -built-in-libraries D:\Program Files (x86)\Arduino\libraries -libraries F:\ArduinoProjcet\libraries -fqbn=Arduino_STM32-master:STM32F1:genericSTM32F103C:device_variant=STM32F103C8,upload_method=STLinkMethod,cpu_speed=speed_72mhz,opt=osstd -ide-version=10805 -build-path C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255 -warnings=none -build-cache C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_cache_508084 -prefs=build.warn_data_percentage=75 -verbose F:\ArduinoProjcet\libraries\STM32F1_RTC\examples\Serial_Clock_and_Calendar\Serial_Clock_and_Calendar.ino
D:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware D:\Program Files (x86)\Arduino\hardware -hardware C:\Users\Liuyiming\AppData\Local\Arduino15\packages -tools D:\Program Files (x86)\Arduino\tools-builder -tools D:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\Liuyiming\AppData\Local\Arduino15\packages -built-in-libraries D:\Program Files (x86)\Arduino\libraries -libraries F:\ArduinoProjcet\libraries -fqbn=Arduino_STM32-master:STM32F1:genericSTM32F103C:device_variant=STM32F103C8,upload_method=STLinkMethod,cpu_speed=speed_72mhz,opt=osstd -ide-version=10805 -build-path C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255 -warnings=none -build-cache C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_cache_508084 -prefs=build.warn_data_percentage=75 -verbose F:\ArduinoProjcet\libraries\STM32F1_RTC\examples\Serial_Clock_and_Calendar\Serial_Clock_and_Calendar.ino
Using board 'genericSTM32F103C' from platform in folder: D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1
Using core 'maple' from platform in folder: D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1
Detecting libraries used...
"C:\Users\Liuyiming\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -w -DDEBUG_LEVEL=DEBUG_NONE -std=gnu++11  -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -DBOARD_generic_stm32f103c -DVECT_TAB_ADDR=0x8000000 -DERROR_LED_PORT=GPIOC -DERROR_LED_PIN=13 -w -x c++ -E -CC -mcpu=cortex-m3 -DF_CPU=72000000L -DARDUINO=10805 -DARDUINO_GENERIC_STM32F103C -DARDUINO_ARCH_STM32F1  -DCONFIG_MAPLE_MINI_NO_DISABLE_DEBUG=1 -DSERIAL_USB -DGENERIC_BOOTLOADER -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/stm32f1/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/stm32f1" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/usb_lib" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\variants\generic_stm32f103c" "C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255\sketch\Serial_Clock_and_Calendar.ino.cpp" -o "nul"
"C:\Users\Liuyiming\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -w -DDEBUG_LEVEL=DEBUG_NONE -std=gnu++11  -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -DBOARD_generic_stm32f103c -DVECT_TAB_ADDR=0x8000000 -DERROR_LED_PORT=GPIOC -DERROR_LED_PIN=13 -w -x c++ -E -CC -mcpu=cortex-m3 -DF_CPU=72000000L -DARDUINO=10805 -DARDUINO_GENERIC_STM32F103C -DARDUINO_ARCH_STM32F1  -DCONFIG_MAPLE_MINI_NO_DISABLE_DEBUG=1 -DSERIAL_USB -DGENERIC_BOOTLOADER -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/stm32f1/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/stm32f1" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/usb_lib" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\variants\generic_stm32f103c" "-IF:\ArduinoProjcet\libraries\STM32F1_RTC\src" "C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255\sketch\Serial_Clock_and_Calendar.ino.cpp" -o "nul"
"C:\Users\Liuyiming\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -w -DDEBUG_LEVEL=DEBUG_NONE -std=gnu++11  -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -DBOARD_generic_stm32f103c -DVECT_TAB_ADDR=0x8000000 -DERROR_LED_PORT=GPIOC -DERROR_LED_PIN=13 -w -x c++ -E -CC -mcpu=cortex-m3 -DF_CPU=72000000L -DARDUINO=10805 -DARDUINO_GENERIC_STM32F103C -DARDUINO_ARCH_STM32F1  -DCONFIG_MAPLE_MINI_NO_DISABLE_DEBUG=1 -DSERIAL_USB -DGENERIC_BOOTLOADER -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/stm32f1/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/stm32f1" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/usb_lib" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\variants\generic_stm32f103c" "-IF:\ArduinoProjcet\libraries\STM32F1_RTC\src" "F:\ArduinoProjcet\libraries\STM32F1_RTC\src\stm32f1_rtc.cpp" -o "nul"
Generating function prototypes...
"C:\Users\Liuyiming\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -w -DDEBUG_LEVEL=DEBUG_NONE -std=gnu++11  -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -DBOARD_generic_stm32f103c -DVECT_TAB_ADDR=0x8000000 -DERROR_LED_PORT=GPIOC -DERROR_LED_PIN=13 -w -x c++ -E -CC -mcpu=cortex-m3 -DF_CPU=72000000L -DARDUINO=10805 -DARDUINO_GENERIC_STM32F103C -DARDUINO_ARCH_STM32F1  -DCONFIG_MAPLE_MINI_NO_DISABLE_DEBUG=1 -DSERIAL_USB -DGENERIC_BOOTLOADER -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/stm32f1/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/stm32f1" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/usb_lib" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\variants\generic_stm32f103c" "-IF:\ArduinoProjcet\libraries\STM32F1_RTC\src" "C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255\sketch\Serial_Clock_and_Calendar.ino.cpp" -o "C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255\preproc\ctags_target_for_gcc_minus_e.cpp"
"D:\Program Files (x86)\Arduino\tools-builder\ctags\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255\preproc\ctags_target_for_gcc_minus_e.cpp"

"C:\Users\Liuyiming\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -w -DDEBUG_LEVEL=DEBUG_NONE -std=gnu++11 -MMD -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -DBOARD_generic_stm32f103c -DVECT_TAB_ADDR=0x8000000 -DERROR_LED_PORT=GPIOC -DERROR_LED_PIN=13 -mcpu=cortex-m3 -DF_CPU=72000000L -DARDUINO=10805 -DARDUINO_GENERIC_STM32F103C -DARDUINO_ARCH_STM32F1  -DCONFIG_MAPLE_MINI_NO_DISABLE_DEBUG=1 -DSERIAL_USB -DGENERIC_BOOTLOADER -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/stm32f1/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/stm32f1" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/usb_lib" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\variants\generic_stm32f103c" "-IF:\ArduinoProjcet\libraries\STM32F1_RTC\src" "C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255\sketch\Serial_Clock_and_Calendar.ino.cpp" -o "C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255\sketch\Serial_Clock_and_Calendar.ino.cpp.o"
Compiling libraries...
Compiling library "STM32F1_RTC"
"C:\Users\Liuyiming\AppData\Local\Arduino15\packages\arduino\tools\arm-none-eabi-gcc\4.8.3-2014q1/bin/arm-none-eabi-g++" -c -g -Os -w -DDEBUG_LEVEL=DEBUG_NONE -std=gnu++11 -MMD -ffunction-sections -fdata-sections -nostdlib --param max-inline-insns-single=500 -fno-rtti -fno-exceptions -fno-use-cxa-atexit -DBOARD_generic_stm32f103c -DVECT_TAB_ADDR=0x8000000 -DERROR_LED_PORT=GPIOC -DERROR_LED_PIN=13 -mcpu=cortex-m3 -DF_CPU=72000000L -DARDUINO=10805 -DARDUINO_GENERIC_STM32F103C -DARDUINO_ARCH_STM32F1  -DCONFIG_MAPLE_MINI_NO_DISABLE_DEBUG=1 -DSERIAL_USB -DGENERIC_BOOTLOADER -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 -DMCU_STM32F103C8  -mthumb  -march=armv7-m -D__STM32F1__ -DARDUINO_ARCH_STM32 "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/stm32f1/include" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/stm32f1" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/usb/usb_lib" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple" "-ID:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\variants\generic_stm32f103c" "-IF:\ArduinoProjcet\libraries\STM32F1_RTC\src" "F:\ArduinoProjcet\libraries\STM32F1_RTC\src\stm32f1_rtc.cpp" -o "C:\Users\LIUYIM~1\AppData\Local\Temp\arduino_build_165255\libraries\STM32F1_RTC\stm32f1_rtc.cpp.o"
In file included from D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include/libmaple/rcc.h:54:0,

                 from D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/include/libmaple/gpio.h:48,

                 from D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple/wirish_types.h:37,

                 from D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple/boards.h:38,

                 from D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple/wirish.h:54,

                 from D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\cores\maple/Arduino.h:30,

                 from F:\ArduinoProjcet\libraries\STM32F1_RTC\src\stm32f1_rtc.h:5,

                 from F:\ArduinoProjcet\libraries\STM32F1_RTC\src\stm32f1_rtc.cpp:2:

F:\ArduinoProjcet\libraries\STM32F1_RTC\src\stm32f1_rtc.cpp: In member function 'void STM32F1_RTC::init()':

D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system/libmaple/stm32f1/include/series/rcc.h:356:48: error: 'RCC_BDCR_RTC_BIT' was not declared in this scope

 #define RCC_BDCR_RTCEN                  (1U << RCC_BDCR_RTC_BIT)

                                                ^

F:\ArduinoProjcet\libraries\STM32F1_RTC\src\stm32f1_rtc.cpp:21:15: note: in expansion of macro 'RCC_BDCR_RTCEN'

   RCC_BDCR |= RCC_BDCR_RTCEN; // Enables the RTC

               ^

**Comment by ZulNs** [comment] 2019-11-07 13:10
It seems that the error was caused by a definition error in Roger Clark's libmaple. This error has been fixed in the latest version, but you can fix it yourself.
Please find the `rcc.h` file in your `D:\Program Files (x86)\Arduino\hardware\Arduino_STM32-master\STM32F1\system\libmaple\stm32f1\include\series` folder. Edit that file, go to line `356` and replace

`#define RCC_BDCR_RTCEN                  (1U << RCC_BDCR_RTC_BIT)`

with

`#define RCC_BDCR_RTCEN                  (1U << RCC_BDCR_RTCEN_BIT)`

**Comment by Liuyiming11** [comment] 2019-11-07 15:31
thanks for you reply,I will try it later!

**Closed as completed** 2019-11-12 16:35 UTC
